<#
.SYNOPSIS
    Sets up the folder structure for Azure AI Foundry project.

.DESCRIPTION
    This script creates a clean directory tree for your Azure AI Foundry project.
    It creates subfolders (datasets, scripts, notebooks, config, logs).
    Each subfolder gets a README.md with its purpose.
    It also generates a master README.md at the project root with:
        - Project overview
        - Folder structure diagram
        - Folder purposes
        - Project milestones tracker

.HOW TO RUN
    1. Open PowerShell
    2. Navigate to the project root:
       cd "C:\Users\massa\Desktop\Python\Reference\AzureAI-Foundry"
    3. Run:
       .\setup_project.ps1
#>

# Define the base path (auto-detects the script's folder)
$BasePath = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host "Setting up Azure AI Foundry project structure at:" $BasePath -ForegroundColor Cyan

# Define folders and their README content
$Folders = @{
    "datasets"  = "### datasets/\n\nThis folder stores all raw and processed datasets."
    "scripts"   = "### scripts/\n\nThis folder contains Python scripts for automation and AI agents."
    "notebooks" = "### notebooks/\n\nThis folder contains Jupyter notebooks."
    "config"    = "### config/\n\nThis folder holds configuration files (.env, JSON, YAML)."
    "logs"      = "### logs/\n\nThis folder stores logs generated by scripts and experiments."
}

# Create folders and add detailed README.md
foreach ($Folder in $Folders.Keys) {
    $FullPath = Join-Path $BasePath $Folder
    if (-Not (Test-Path $FullPath)) {
        New-Item -ItemType Directory -Path $FullPath | Out-Null
        Write-Host "Created folder:" $FullPath -ForegroundColor Green
    }
    else {
        Write-Host "Folder already exists:" $FullPath -ForegroundColor DarkGray
    }

    # Add README with purpose text
    $ReadmePath = Join-Path $FullPath "README.md"
    $Folders[$Folder] | Out-File -FilePath $ReadmePath -Encoding utf8
    Write-Host "Updated README in:" $ReadmePath -ForegroundColor Yellow
}

# Create master README.md at project root
$MasterReadme = @"
#### Azure AI Foundry Project  

---

#### 📌 Purpose  
This repository contains all resources, scripts, and documentation for learning and building with **Azure AI Foundry**.  

---

#### 📂 Folder Structure Overview  

AzureAI-Foundry/
│── 01_environment_setup.md        # Documentation of environment setup
│── 02_setup_project_structure.md  # Documentation of project structure
│── setup_project.ps1              # Script to create folders + READMEs
│── test_foundry_connection.py     # Script to test Foundry connection
│── README.md                      # Project overview (this file)
│
├── datasets/      # Raw & processed datasets
├── scripts/       # Python automation scripts
├── notebooks/     # Jupyter notebooks for lessons/experiments
├── config/        # Configuration files (.env, JSON, YAML)
└── logs/          # Logs from experiments & agents

---

#### 📊 Project Milestones  

- ✅ Environment Setup  
- ✅ Project Structure Organized  
- ⬜ Week 1: Azure AI Foundry — First Dataset Upload & Exploration  
- ⬜ Week 2: Prompt Flow — Build Your First Copilot  
- ⬜ Week 3: Data Integration — Connect SQL Server & PostgreSQL  
- ⬜ Week 4: Deploying an AI Agent to Azure  
- ⬜ Week 5+: Advanced Topics  
"@

$MasterReadmePath = Join-Path $BasePath "README.md"
$MasterReadme | Out-File -FilePath $MasterReadmePath -Encoding utf8
Write-Host "✅ Master README created/updated at:" $MasterReadmePath -ForegroundColor Cyan

Write-Host "✅ Project structure setup complete with detailed READMEs + Master README + Milestones!" -ForegroundColor Cyan
